### PR TITLE
My suggestion for statusline visibility issue #26 (again)

### PR DESCRIPTION
**Pull request by demokritos**
Sorry. I closed #337 because "follow hint" did not work in google search pages if statusline was hidden. That seems not my problem. pizzood's code shows the same behavior.
So I again pull request.

From #337:
I mended my old code for #26 a bit. This replaces pizzood's code and provides users a possibility to change the statusline's visibility.

### CODE REVIEW

**Comment by polyzen** [comment]
Just so you know, you can update a pr by editing the branch behind it. No need to make a new pr :)

**Comment by demokritos** [comment]
Thank you, @polyzen.
As I wrote, I had to make this pull request because I had closed the previous pull request.

**Comment by polyzen** [comment]
@demokritos, oh, I missed that. Surprised it doesn't let you re-open it.

**Comment by maxauthority** [comment]
So before I test it properly: The "expected" result is to just hide the
statusbar automatically if you enter fullscreen (not just with :set
fullscreen, but also by using youtube, F11, etc.), but if you press : it'll
show up temporarily until you finish the command. Is that how it works?
Then I'll take a closer look.

On Sun, Nov 22, 2015 at 7:03 PM, Daniel M. Capella <notifications@github.com

**Comment by demokritos** [comment]
Do you mean that you do not expect the statusbar not to show up while command input?
This PR will hide the statusbar if you enter fullscreen (in any way).
It temporarily unhide the statusbar when the commandline needed, such as when you press `:` to input command, when you press `;` to do the link actions. If you finish that, it will automatically hide the statusbar. This behavior is the same as pizzood's commit, except that my PR will not show up the statusbar while INSERT, CARET mode.
Though same functionality is provided by pizzood's commit, I suggest this PR because pizzood's commit does not allow users to manually hide and unhide the statusbar. Whith my PR, users can unhide the statusbar in fullscreen mode or hide it in non-fullscreen mode.

**Comment by maxauthority** [comment]
I tested it and seems to work great! Can you please add an entry to the vimperator/NEWS file for the new functionality, then I'll merge it.

**Comment by demokritos** [comment]
Thank you. I edited the NEWS file.

**Pull request merged**
