### PR TITLE
Add option for controlling passthrough to webpages

### LINKED ISSUE #286: Quickmarks not fully functioning
On certain pages, some quickmarks seems to fail; for example, having a quickmark "y" pointing to youtube.com; and being on https://github.com/vimperator/vimperator-labs; when typing "gny", instead of opening up a new tab with youtube, something loads https://github.com/vimperator/vimperator-labs/tree/ba7d8e72516fdc22246748c8183d7bc90f6fb073 into current tab. Also quickmark action is still enabled, so as soon I for example hits delete to remove text, I get `Quickmark not set: <Del>`.

### PR DESCRIPTION
**Pull request by Enzime**
Allows you to stop keypresses being passed to webpages when you are outside of Insert/Passthrough modes. Fixes #286.

### CODE REVIEW

**Comment by polyzen** [comment]
Passthrough mode on pentadactyl works great. You can toggle it with ctrl-z; perhaps this can be added?

**Comment by jvdm** [comment]
*Finally* a fix for this.

**Comment by maxauthority** [comment]
Well, it's not yet pushed to master. But I agree, it doesn't hurt and actually should be in Vimperator (probably even by default in future). Can you please update the pull request (I guess the things in the NEWS are conflicting), and I'll merge it?

**Comment by polyzen** [comment]
I suppose that's a no on including a default keybinding

**Comment by maxauthority** [comment]
Well we still/already have a keybinding to pass all keys to the web page
(S-Insert). I don't see the point of toggling just passing unused keys to
the web page. I guess that should be enough. And if you really need to
toggle that often (why?) you can still :map a key to :set invpassthrough<cr>

**Comment by polyzen** [comment]
Sorry, I misunderstood this pr :p

**Comment by Enzime** [comment]
Fixed the NEWS, hope to see this merged soon

**Pull request merged**
