### PR TITLE
Fix #566: Extend makefile for signing

### LINKED ISSUE #566: Extend makefile for signing
Since Firefox 48 it is not possible to disable the signature verification for add-ons. There is an API to sign add-ons semi-automatically: https://addons-server.readthedocs.io/en/latest/topics/api/signing.html

Following modifications to the Makefile are necessary:

- Change the UUID of the XPI to a custom one (read from a configuration file)
- Also read the API user and token from the configuration file
- Increment the version to something unique (e.g. `${VERSION}.$(date '+%Y%m%d%H%M%S')`)
- Submit XPI via the API and check the response code.
- On positive response, check every 1 minute if the XPI is ready for download
- When ready, download signed XPI

### PR DESCRIPTION
**Pull request by SammysHP**
Still experimental, but I tested it successfully.

### CODE REVIEW

**Comment by SammysHP** [comment]
Btw: This requires jpm: https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/jpm

**Comment by gkatsev** [comment]
Oh it works?
Last time I tried it, it said that vimperator couldn't be autosigned.

Also, it would be good if we add a `package.json` that makes `jpm` a `devDep` and then add npm scripts to run jpm. Then, the makefile can call it through that. Would make everything more reproducible and self contained.

**Comment by SammysHP** [comment]
AFAIK autosigning works only for unlisted packages.

> Under the hood, jpm sign creates an unlisted add-on inside addons.mozilla.org, which means you must distribute the XPI file yourself for your users to install it. If you need to create a listed add-on, just submit it directly to addons.mozilla.org where it is signed automatically.

(from above link)

**Comment by gkatsev** [comment]
Aaah, I see.

**Comment by maxauthority** [comment]
So is this still useful? Then I'll merge the request.

**Comment by SammysHP** [comment]
So what do you want to do with this PR? I'm using it even for development (signing takes only 1 minute and by default the version code is incremented every second) and it works great. But the release would still require a manual upload.

**Comment by timss** [comment]
Considering the amount of pressure coming from widespread issues such as #590, I think this should be merged and nightlies set up. What do you think @gkatsev and @maxauthority ?

I could help set up nightlies. Shouldn't be harder than a cronjob and hosting it on vimperator.org somewhere.

**Comment by maxauthority** [comment]
Yeah, nightlies would be fine. However, since that addon has a different UID, doesn't this mean, that the user is never automatically updated to the "official" version once it gets approved by AMO? I guess that could cause some nasty problems :(

Additionally, I fear they can't be (automatically) hosted on vimperator.org as that's basically a "google sites" site, not a real virtual server which I have full control of :( Can github be setup to create nightlies somehow?

But anyway, sorry for not pulling the request in time (I think it needs a slight modification to be merged now). Since it does not break anything, and is beautifully written, I'd merge it as soon as possible (if you can fix the conflicts).

**Comment by SammysHP** [comment]
I'll rebase the change tomorrow.

Regarding nightlies: Yes, they will have a different UID, but they can be updated automatically via the `updateURL` property in the manifest file: https://developer.mozilla.org/en-US/Add-ons/Install_Manifests#updateURL

I can add a dynamic property to the new `private.properties` files. But first I have to test if automatic signing works with updateURL.

Regarding hosting: updateURL requires https. AFAIK GitHub supports file uploads via API to each release (thus each nightly would require a release). But I'm not sure if GitHub is a good solution for that use case.

Regarding "GitHub for nightlies": Yes, GitHub has complex CI server support, but that would require an own CI server (or some hosted server). For example every commit could trigger a code check or nightly build.

TODO for me:

- [ ] Rebase commit
- [ ] Check updateURL support
- [ ] Add updateURL to private.properties

**Comment by timss** [comment]
Automatic update/upgrade to AMO could be handy, but if the alternative is having no nightlies I don't think it should be a showstopper.

We could maybe create a new repo in the vimperator group, and ship all the nightly builds there as releases if it's possible to use the API somehow? Even fancier, only trigger build on commits to master (maybe overkill).

**Comment by SammysHP** [comment]
Btw: I'd just read about the possibilities of jpm. Using it would definitely improve the process of generating an XPI (used in the makefile). I think this would be a good start to clean up the add-on structure and Manifest file.

https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/jpm

**Comment by SammysHP** [comment]
This should work. It still requires a proper *.rdf update file at that url.

**Comment by SammysHP** [comment]
I added an `update.rdf` template and extended the makefile. You can find an example here:
https://krul.finf.uni-hannover.de/~sammyshp/vimperator/

I'm not sure if this is really necessary, so decide yourself what you want to merge (and if you don't squash you can revert parts of it easily later).

PS: And sorry, that I registered vimperator-nightly@mozdev.org some time ago. But that domain isn't suitable anyway. ;)

**Comment by maxauthority** [comment]
The update.rdf support doesn't hurt, so I merged it as a whole. Let's just hope it doesn't break the non-nightly builds which are manually uploaded to AMo.

**Comment by SammysHP** [comment]
Just don't set `UPDATE_URL` in `private.properties`. Even better: Don't use `private.properties` at all because then it should work exactly as previously.

**Pull request merged**
