### PR TITLE
Toggle reader view with gr

### PR DESCRIPTION
**Pull request by seanmorton**
Ref #262.

Adds command ```gr``` to toggle Reader View.

### CODE REVIEW

**Comment by gkatsev** [comment]
How is this different from #262? That one seems to toggle it with `gr` as well.

**Comment by seanmorton** [comment]
It is essentially the same, but rather than depending on clicking ```"View:ReaderView"```, it manipulates the url to use the ```about:reader?url=``` scheme. Also, I added the feature in the NEWS file.

**Comment by mcarton** [comment]
Firefox's `toggleReaderMode` function is more complicated than yours and yours does not seem to actually display an error message when the reader mode can't open the current page. Also `uri.match(/about:reader/)` is not sufficient as that matches `http://foo.bar/about:reader`.
As for using `View:ReaderView` why would you avoid it? (I'm not familiar with either firefox, vimperator or JS so I did what I could)

**Comment by seanmorton** [comment]
There's probably nothing wrong with using ```View:ReaderView```. I just got the idea to use the ```about:reader``` method from the following function in the reader mode source:

```
# https://mxr.mozilla.org/mozilla-release/source/toolkit/components/reader/ReaderMode.jsm
89   /**
90    * Returns original URL from an about:reader URL.
91    *
92    * @param url An about:reader URL.
93    * @return The original URL for the article, or null if we did not find
94    *         a properly formatted about:reader URL.
95    */
96   getOriginalUrl: function(url) {
97     if (!url.startsWith("about:reader?")) {
98       return null;
99     }
100 
101     let searchParams = new URLSearchParams(url.substring("about:reader?".length));
102     if (!searchParams.has("url")) {
103       return null;
104     }
105     let encodedURL = searchParams.get("url");
106     try {
107       return decodeURIComponent(encodedURL);
108     } catch (e) {
109       Cu.reportError("Error decoding original URL: " + e);
110       return encodedURL;
111     }
112   }
```

Owners, please let us know which method you would prefer. mcarton, I do think that the ```:reader``` command should be added alongside ```gr```, so I'll add that in if the owners decide to go with this method. I'll also work out the bugs you mentioned above.

**Comment by maxauthority** [comment]
For, me just having "gr" alone without any command or option is ok to be
merged. (and we still have :emenu for those who really need a command).

**Comment by seanmorton** [comment]
I've tested this and it should now be ready to merge.

**Comment by seanmorton** [comment]
#262 can also be closed. Thanks!

**Comment by jordila** [comment]
gr might be quite useful.thanks!

Still... it's not working when i try it 
[screencast](https://dl.dropboxusercontent.com/u/18889627/Screencasts/gr-vimperator-command-failed.webm)
what am i missing ?

**Pull request merged**
