### PR TITLE
capture keydown event to handle escaping in every case

### PR DESCRIPTION
**Pull request by severtsev**

### CODE REVIEW

**Comment by gkatsev** [comment]
Thanks! I'll take a look soon.

**Comment by maxauthority** [comment]
I merged it after testing it for a while and seems to work fine. Please report any issues which I haven't caught testing. Thanks for the patch!

**Comment by SammysHP** [comment]
This causes #198.

**Comment by maxauthority** [comment]
I had to revert this fix as it causes #198. Maybe there is a better fix, which doesn't cause the issues in that bug, as otherwise the patch would have worked fine and fixes the annoying Esc not always working problem.

**Comment by derenio** [comment]
Just to keep the track of things, the revert also reopens #46.

**Pull request merged**
