### PR TITLE
Delete deprecated template literals

### PR DESCRIPTION
**Pull request by gineadai**

### CODE REVIEW

**Comment by maxauthority** [comment]
+4 lines, -572 lines -> I love such commits which get rid of old/obscure stuff!

Since it's a rather big commit, has anyone tested it and found some problems? Otherwise I'd like to merge it soon.

**Comment by gkatsev** [comment]
I can give it a whirl over the weekend.

**Comment by gineadai** [comment]
I don't think it's needed to be credited in changelog. It's just cleaning up. But if you going to do it, credit @caisui as well.

**Comment by gkatsev** [comment]
I'll make sure to mention @caisui, @gineadai.

**Pull request merged**
