### PR TITLE
Use '===' & '!==' instead of '==' & '!='

### PR DESCRIPTION
**Pull request by emphonst**
Reccomendation from static code analysis (jshint.com, jslint.com).

### CODE REVIEW

**Comment by timss** [comment]
Probably a good idea, but it seems to me that even if it should not™ introduce breakage it still needs thorough testing because of unexpected conversions.

Have you verified it's working, it did you just do a global search and replace (sed, or similar)?

**Comment by emphonst** [comment]
Something broken. I hastened with pull request. Better to test more.

**Comment by timss** [comment]
You can continue adding commits to a pull request by pushing to your branch (`emphonst:jshint`). If necessary they can be squashed on merge, so no big need to close :)

**Comment by emphonst** [comment]
@tmss I replace only what was showing as error in jshint, and avoid `==null` and `!= null`, because it casue breakage on some point and need thorough testing.

**Comment by timss** [comment]
I haven't been able to test this myself yet, since so much is changed I'm not quite sure where to start looking or if maybe just applying the changes and use vimperator a while is the way to go.

What's your current status, @ghost? Seeing as you closed the issue again.

**Pull request closed without merging**
