### PR TITLE
fix Shift+Insert paste on Linux

### LINKED ISSUE #560: shift insert erase text
##### Issue type:

- Bug report

##### Version:

```
Vimperator:	3.14.0 (created: 2016/06/07 23:58:16)
Firefox:	Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0
```

##### Description:

When inserting some text from the *selection buffer* into a text area (as for example the one for filling new bug report on github) using SHIFT+Insert, the text is written where the cursor is however everything below it is completely removed.

##### Expected behavior:

I would expect the text to be pasted where the cursor is without actually erasing what remains after.

##### Steps to reproduce:

see *Description* above. This happens in any editable text area.

### PR DESCRIPTION
**Pull request by benoit-pierre**
Do not delete the text after the cursor/selection. Fix #560.

### CODE REVIEW

**Comment by timss** [comment]
I'll try this tonight, and probably merge it :+1:

**Comment by timss** [comment]
Thanks @benoit-pierre

**Comment by pale3** [comment]
@timss, @benoit-pierre 
Please revert this merge, the reason is that pasting xselection if leftover buffer is example open, xselection will be prepended so for example it will look like this: 

```open my xselect pasteamazon```
```open my xselect pastegoogle```

part of amazon/google or any search engine is constructed in tempStr3 as leftover string. 
Please take a look at my conversation and 3rd comment of maxauthority for more info #452

**Comment by benoit-pierre** [comment]
I don't understand, you mean you're starting in this state (`|` represent the cursor position):
```
open |amazon
```
with the xselection set to `my xselect paste` and you press shift+insert?

Because in that case the result is expected, and you should get:
```
open my xselect paste|amazon 
```

**Comment by benoit-pierre** [comment]
OK, I see what you mean now, I think what's missing is a call to clear the completions preview:
```diff
diff --git i/common/content/editor.js w/common/content/editor.js
index 4727a09..7f51e67 100644
--- i/common/content/editor.js
+++ w/common/content/editor.js
@@ -70,6 +70,9 @@ const Editor = Module("editor", {
                 return;
             }

+            if (commandline._completions)
+                commandline._completions.previewClear();
+
             let elem = liberator.focus;

             if (elem.setSelectionRange && util.readFromClipboard()) {
```

**Comment by pale3** [comment]
@benoit-pierre 
Yep, this is it, thx for fast solution ;). 

@timss 
please merge this! it will fix leftover string from buffer when pasting

**Comment by timss** [comment]
@pale I'm sorry, but I can't reproduce a situation where xselection is prepended somehow. 

Do you mean that if the buffer is:

    :open google|

and you press `S-Insert` at `|`, you get this?

    :open <selection>google

Tried your patch @benoit-pierre, but not able to see the difference. 

---

Reverting a PR and making a new merge seems to be somewhat messy. Maybe it's easiest to just make a new PR with the change if you want the commit, @benoit-pierre. Other suggestions welcome.

**Comment by benoit-pierre** [comment]
See my comment on #569.

**Comment by timss** [comment]
Ah, I get it now, thanks :)

**Comment by timss** [comment]
@pale3 Fixed in f9cd1ef

**Comment by pale3** [comment]
thx guys

**Pull request merged**
