### PR TITLE
 TODO: delete me when minVersion is greater than 34

### PR DESCRIPTION
**Pull request by gineadai**
Only what i could made out. I made xpi (vimperator and muttator) and check both - work the same.

### CODE REVIEW

**Comment by maxauthority** [comment]
Sounds good to me, and pushing minVersion to at least 35 sounds reasonable given that that version should be at least a year old.

**Comment by gkatsev** [comment]
Our min version is already 38.

**Comment by timss** [comment]
Which, in a few days, is about a year old.

https://en.wikipedia.org/wiki/History_of_Firefox#Version_38

**Comment by gkatsev** [comment]
Assuming everything still works, LGTM.

**Comment by gineadai** [comment]
I added commit, how to revert it? i want it to be in next pull request after this is merged.

**Comment by gkatsev** [comment]
you can do something like `git revert --hard HEAD~1` which should put you in the previous commit, you can check by typing `git show`. Afterwards, just `git push --force`.

**Comment by gineadai** [comment]
I don't use git yet. So just reverted changes for now. Added two hollow commits.

**Comment by gineadai** [comment]
I want to make new pull request. How i can isolate current pull request?

**Comment by caisui** [comment]
If remove template.js, remove more.

```patch
From bb18fcbb19b720262ec013a0f0e836a722e58c57 Mon Sep 17 00:00:00 2001
From: caisui <rincaisui@gmail.com>
Date: Mon, 9 May 2016 21:14:33 +0900
Subject: [PATCH] remove code for support template literal(<Fx34)

---
 common/components/protocols.js      | 118 +-----------------------------------
 common/content/javascript.js        |   3 -
 common/content/liberator-overlay.js |   8 +--
 common/modules/CheckTemplate.jsm    |  11 ----
 4 files changed, 3 insertions(+), 137 deletions(-)
 delete mode 100644 common/modules/CheckTemplate.jsm

diff --git a/common/components/protocols.js b/common/components/protocols.js
index 3ad7705..cda8638 100644
--- a/common/components/protocols.js
+++ b/common/components/protocols.js
@@ -16,11 +16,6 @@ const { classes: Cc, interfaces: Ci, utils: Cu } = Components;
 
 Cu.import("resource://gre/modules/Services.jsm");
 Cu.import("resource://gre/modules/XPCOMUtils.jsm");
-XPCOMUtils.defineLazyGetter(this, "convert", function () {
-    var obj = new Object;
-    Cu.import("resource://liberator/template.js", obj);
-    return obj.convert;
-});
 
 const NS_BINDING_ABORTED = 0x804b0002;
 const nsIProtocolHandler = Ci.nsIProtocolHandler;
@@ -51,17 +46,6 @@ function redirect(to, orig) {
     let html = '<html><head><meta http-equiv="Refresh" content="' + ("0;" + to).replace(/"/g, "&quot;") + '"/></head></html>';
     return makeChannel(dataURL('text/html', html), ioService.newURI(to, null, null));
 }
-XPCOMUtils.defineLazyGetter(this, "cache", function () {
-    var dir = Cc["@mozilla.org/file/directory_service;1"].getService(Ci.nsIProperties).get("ProfD", Ci.nsIFile);
-    dir.append("liberatorCache");
-    if (!dir.exists()) {
-        dir.create(dir.DIRECTORY_TYPE, -1);
-    }
-    return dir;
-});
-XPCOMUtils.defineLazyGetter(this, "version", function () {
-    return Services.appinfo.version;
-});
 
 function ChromeData() {}
 ChromeData.prototype = {
@@ -147,111 +131,11 @@ Liberator.prototype = {
                     .createInstance(Ci.nsIStandardURL)
                     .QueryInterface(Ci.nsIURI);
         uri.init(uri.URLTYPE_STANDARD, this.defaultPort, spec, charset, baseURI);
-
-        if (uri.host !== "template") return uri;
-
-        try {
-        spec = uri.spec;
-        //uri.init(uri.URLTYPE_STANDARD, this.defaultPort, uri.path.substr(1), charset, null);
-        // xxx:
-        uri = ioService.newURI(uri.path.replace(new RegExp("^/+"), ""), charset, null);
-        // recursible when override
-        while (uri.scheme === "chrome") {
-            uri = Cc["@mozilla.org/chrome/chrome-registry;1"]
-                .getService(Ci.nsIChromeRegistry)
-                .convertChromeURL(uri);
-        }
-
-        var nest = Cc["@mozilla.org/network/util;1"].getService(Ci.nsINetUtil).newSimpleNestedURI(uri);
-        nest.spec = spec;
-        } catch (ex) { Cu.reportError(ex); }
-        return nest;
+        return uri;
     },
 
     newChannel: function (uri) {
         try {
-            if ((uri instanceof Ci.nsINestedURI)) {
-                var m = (new RegExp("^/{2,}([^/]+)/([^?]+)")).exec(uri.path);
-                if (m) {
-                    var host = m[1];
-                    var path = m[2];
-
-                    switch (host) {
-                    case "template":
-                        try {
-                        var nest = ioService.newURI(path, uri.charset, null);
-                        var channel = ioService.newChannelFromURI(nest);
-
-                        // xxx: support template
-                        if (0) return channel;
-
-                        // xxx: NG: Firefox 16, 17
-                        //      NG: Cu.import
-                        if (parseFloat(version) < 17) {
-                            var stream = Cc["@mozilla.org/scriptableinputstream;1"]
-                                            .createInstance(Ci.nsIScriptableInputStream);
-                            var cstream = channel.open();
-                            stream.init(cstream);
-                            var text = stream.read(-1);
-                            stream.close();
-                            cstream.close();
-
-                            stream = Cc["@mozilla.org/io/string-input-stream;1"].createInstance(Ci.nsIStringInputStream);
-                            stream.setData(convert(text), -1);
-                            var channel = Cc["@mozilla.org/network/input-stream-channel;1"]
-                                .createInstance(Ci.nsIInputStreamChannel);
-			                channel.contentStream = stream;
-                            channel.QueryInterface(Ci.nsIChannel);
-                            channel.setURI(uri);
-                            return channel;
-                        }
-
-                        var innerURI = uri.innerURI;
-                        var temp = cache.clone();
-                        var path = nest.spec.replace(/[:\/]/g, "_");
-                        var lastModifiedTime;
-                        if (innerURI.scheme === "resource") {
-                            innerURI = Cc["@mozilla.org/network/protocol;1?name=resource"]
-                                .getService(Ci.nsIResProtocolHandler).resolveURI(innerURI);
-                            innerURI = ioService.newURI(innerURI, null, null);
-                        }
-                        if (innerURI.scheme === "jar") {
-                            innerURI = innerURI.QueryInterface(Ci.nsIJARURI).JARFile;
-                        }
-                        if (innerURI.scheme === "file") {
-                            lastModifiedTime = innerURI.QueryInterface(Ci.nsIFileURL).file.lastModifiedTime;
-                        } else {
-                            Cu.reportError("do not support:" + innerURI.spec);
-                        }
-
-                        temp.append(path);
-                        if (!temp.exists()
-                            || temp.lastModifiedTime !== lastModifiedTime) {
-
-                            var stream = Cc["@mozilla.org/scriptableinputstream;1"]
-                                            .createInstance(Ci.nsIScriptableInputStream);
-                            var cstream = channel.open();
-                            stream.init(cstream);
-                            var text = stream.read(-1);
-                            stream.close();
-                            cstream.close();
-
-                            text = convert(text);
-
-                            var stream = Cc["@mozilla.org/network/file-output-stream;1"].createInstance(Ci.nsIFileOutputStream);
-                            Services.console.logStringMessage("create:" + temp.leafName);
-                            stream.init(temp, 0x2 | 0x8 | 0x20, 0644, 0);
-                            stream.write(text, text.length);
-                            stream.close();
-                            temp.lastModifiedTime = lastModifiedTime;
-                        } else { Services.console.logStringMessage("use cache:" + uri.spec); }
-                        return ioService.newChannelFromURI(ioService.newFileURI(temp));
-                        } catch (ex) { Cu.reportError(ex); }
-                    }
-                }
-                return fakeChannel(uri);
-            }
-
             let url;
             switch(uri.host) {
                 case "help":
diff --git a/common/content/javascript.js b/common/content/javascript.js
index 1f6d460..3187734 100644
--- a/common/content/javascript.js
+++ b/common/content/javascript.js
@@ -637,8 +637,5 @@ const JavaScript = Module("javascript", {
         options.add(["inspectcontentobjects"],
             "Allow completion of JavaScript objects coming from web content. POSSIBLY INSECURE!",
             "boolean", false);
-        options.add(["expandtemplate"],
-                "Expand TemplateLiteral",
-                "boolean", !("XMLList" in window));
     }
 })
diff --git a/common/content/liberator-overlay.js b/common/content/liberator-overlay.js
index c489e62..6785f96 100644
--- a/common/content/liberator-overlay.js
+++ b/common/content/liberator-overlay.js
@@ -5,10 +5,7 @@
 
 (function () {
     const modules = {};
-    // TODO: FIXME when minVersion is greater than 34
-    var {isSupport: TemplateIsSupport} = Components.utils.import("resource://liberator/CheckTemplate.jsm", {});
-    const BASE = TemplateIsSupport ?
-        "chrome://liberator/content/" : "liberator://template/chrome://liberator/content/";
+    const BASE = "chrome://liberator/content/";
 
     modules.modules = modules;
 
@@ -33,8 +30,7 @@
 
     let prefix = [BASE];
 
-    // TODO: FIXME when minVersion is greater than 34
-    Components.utils.import("resource://liberator/template-tag" + (TemplateIsSupport ? ".js" : "-old.js"), modules);
+    Components.utils.import("resource://liberator/template-tag.js", modules);
 
     // TODO: This list is much too long, we should try to minimize
     // the number of required components for easier porting to new applications
diff --git a/common/modules/CheckTemplate.jsm b/common/modules/CheckTemplate.jsm
deleted file mode 100644
index fc89977..0000000
--- a/common/modules/CheckTemplate.jsm
+++ /dev/null
@@ -1,11 +0,0 @@
-// vim: ft=javascript
-// TODO: delete me when minVersion is greater than 34
-
-var EXPORTED_SYMBOLS = ["isSupport"];
-
-try {
-    var isSupport = eval("((a,b)=>a.length)`${1}` === 2");
-} catch (ex) {
-    Components.utils.reportError(ex);
-    isSupport = false;
-}
-- 
2.7.0

```

**Pull request closed without merging**
