### PR TITLE
Make gw opening quickmark in new window

### PR DESCRIPTION
**Pull request by stemar94**

### CODE REVIEW

**Comment by maxauthority** [comment]
I guess, this just is consistent with the other commands (although I dislike multiple windows in a browser, but that's just my personal preference), although we start running out of g* mappings soon ;)

For this to be merged, we need an entry in the NEWS file and in the documentation.

**Comment by stemar94** [comment]
Should I create new branch and merge or can you do this. I guess the NEWS files has merge problems.

**Comment by maxauthority** [comment]
Please update the branch, so I can pull the request. And yeah, I know that there are easily conflicts with the NEWS file, but if we don't update it while adding features, I am sure that will be forgotten when the next version will be released.

**Comment by stemar94** [comment]
Sry I'm totally failing to update. Will be ready shortly.

**Comment by stemar94** [comment]
moved to branch gw3, since I do not know how git works

**Pull request closed without merging**
