### PR TITLE
Open downloads and addons in new tab

### PR DESCRIPTION
**Pull request by stemar94**

### CODE REVIEW

**Comment by Enzime** [comment]
I don't think this should be changed, even though it is confusing I believe the reason it is like this is so you can actually open it in the current tab, with the changes you have provided there is no easy way to open these in the current tab anymore. Currently, if you want to open downloads or addons in a new tab you can use `:tab downloads`

**Comment by benoit-pierre** [comment]
You can also use `set newtab+=addons,downloads` to get the addons/downloads commands to open a new tab.

**Comment by stemar94** [comment]
Cool thanks guys. Didn't know about this.

**Comment by maxauthority** [comment]
I guess, we might change the newtab option though. We should at least be consistent so that the user always gets the expected thing. So opening a new tab for all these things is probably the best default?

**Pull request closed without merging**
