### PR TITLE
remove trailing whitespace

### PR DESCRIPTION
**Pull request by lazysoundsystem**
Following up on https://github.com/vimperator/vimperator-labs/pull/636 (though I added an extra space in the search expression on that ticket), this removes trailing whitespace as per the contribution guidelines.

Checking with `git diff -w` shows that nothing else has been changed.

Thanks for vimperator!

### CODE REVIEW

**Comment by timss** [comment]
Thanks for your contribution. Left a comment, but other than that it looks good.

The changes are somewhat disruptive to the change history of quite a few core files, wouldn't want to repeat this process too often. I take it this is maybe automated and complete (for now)? :-)

**Comment by soredake** [comment]
@timsd http://editorconfig.org/

**Comment by lazysoundsystem** [comment]
Updated the patch by reinstating the spaces within CDATA. 

I believe this is complete - `grep -nr "[[:space:]]\$" .` - There's no need to merge this patch, I just thought I ought to follow up on my comment on the other PR.

By the way, unrelated to this I did notice a reference to "trac" in vimperator/locale/ja/intro.xml and to "googlecode" in vimperator/locale/en-US/intro.xml . Perhaps those need updating.

**Comment by timss** [comment]
Thanks. Merging. 

Yeah, those references need to be fixed and/or removed. Thanks for the heads up. One of them even points to an AUTHORS file which hasn't been updated since 2010 (authors generated based on git log/github is better a nyway).

**Pull request merged**
