### PR TITLE
Split Vimperator syntax highlighting to seperate repo

### PR DESCRIPTION
**Pull request by timss**
Main motivation is to make it easier to install, especially with popular Vim plugin managers such as Vundle or Pathogen.

https://github.com/vimperator/vimperator.vim – Full commit history is included.

### CODE REVIEW

**Comment by timss** [comment]
Hm, why is this still "in progress", @gkatsev ?

**Comment by maxauthority** [comment]
I just looked at this as well. I think both approaches (keeping vimperator.vim in this repo, or in a separate) have both advantages.

But isn't a VimBall (.vba) the "official" vimscript distribution format? It seem this isn't supported anymore in the new Repo.

However, since I am not the main target user, maybe we have some more opinion about the issue how we handle the vimperator.vim scripts in future?

**Comment by gkatsev** [comment]
not quite sure what it's "in progress" and vimballs aren't really official and they're a pain and no one likes them, really. Most people just use a git repo or just a folder with a set structure that things like pathogen can load.

**Comment by timss** [comment]
I'm not sure if many people know that vimperator syntax highlighting is included in the current repo because it's rather hidden. I haven't seen it referenced much at all, and yeah, vimballs are a pain.

Second to being easier to install, splitting it to a seperate repo might also help make people aware of it.

If you think it should be merged in the current state, I'll look into fixing the branch conflicts. Any +1s? :-)

**Comment by timss** [comment]
Looks like I was able to successfully fix my branch diverging/conflicting branch without messing up, yay.

Merging.

**Pull request merged**
