### PR TITLE
Fix scrolling

### LINKED ISSUE #278: Unable to use `gg`, `G` and marks on some websites
On some website scrolling with `gg`, `G` or marks does not work.
Example of such websites:
  - https://groups.google.com/a/isocpp.org/forum/?fromgroups#!forum/std-discussion
  - https://blog.wikimedia.org/

Trying to set a mark with `ma` cause the following message:
```
Added local mark: a, https://blog.wikimedia.org/, (0%, 0%)
```
even if you're not in the top-left of the page. Then trying to jump with `'a` does nothing. `gg` and `G` do nothing either.

Navigation is still possible with `hjkl` and other features seem to work too.

### PR DESCRIPTION
**Pull request by Enzime**
Fixes #278 on many sites :)

### CODE REVIEW

**Comment by gkatsev** [comment]
I'll want to try it out locally before pulling it in but LGTM.

**Comment by gkatsev** [comment]
Works great. Thanks.
This also fixes #373.

**Comment by timss** [comment]
Cool, thanks.

**Comment by timss** [comment]
Hm, I haven't been to find out why or the proper solution, but the changes done to `scrollByScrollSize()` broke scrolling on some pages that used to work.

Reverting 1d88ed3 fixes it, but naturally breaks the sites it didn't previously work with.

Works: https://confluence.atlassian.com/pages/viewpage.action?pageId=339739187
Broken: http://www.tv2.no/sport/7996589/

And vice versa pre 1d88ed3.

**Comment by gkatsev** [comment]
@timss I looked at this a bit. Can you actually open another issue for this? Particuarly with the link to the tv2.no url?
I don't think that this fix is necessarily bad. We probably need to do a better job at figuring out if we should do `window.scrollTo` or use `element.scrollTop`.

**Comment by timss** [comment]
@gkatsev There you go.

**Comment by gkatsev** [comment]
Awesome, thanks.

**Pull request merged**
