### PR TITLE
[{a}] is better to be written in dot notation

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by gkatsev** [comment]
LGTM, thanks.

**Comment by maxauthority** [comment]
Well, is it "technically" any better? I think the reason was, that options["showstatuslinks"] much more highlights that this is an option which is settable with :set that options.showstatuslinks.

If all active developers agree on the later, it's still OK for me to be merged, but I am yet too the advantage of the later for this particular case of options.

**Comment by gkatsev** [comment]
The main reason why I think it's generally better to use dot notation over bracket notation is that it's slightly cleaner and clearer because there's less other stuff going on (quotes and brackets and what not).
I can sort of see the argument that options specifically should still be called via the bracket notation for extra emphasis that they are options but I'm not sure it really adds much. It's almost always called as `options.showstatuslinks`, so, hopefully the `options` there is obvious as well.

**Comment by klaplong** [comment]
I agree with the dot notation as well. Variable names should document themselves, so if one has to use a different syntax for variables to be more clear it means to me they should be renamed.

See [this article](http://a-nickels-worth.blogspot.nl/2016/04/a-guide-to-naming-variables.html) for a more elaborate argumentation.

**Comment by timss** [comment]
Brackets or dots, I think consistency is key. 
If it helps erase minor style differences in the code, I'm positive.

**Comment by maxauthority** [comment]
OK pursaded, I just pulled the request. Thanks.

**Pull request merged**
