### PR TITLE
Add support for the Reader View

### PR DESCRIPTION
**Pull request by mcarton**
Ref #238.

### CODE REVIEW

**Comment by gkatsev** [comment]
Awesome, thanks. I'll get to this ASAP.

**Comment by keitheis** [comment]
Awesome! Looking forward to toggleReaderView.

**Comment by seanmorton** [comment]
I'd love to see this merged as well.

**Comment by maxauthority** [comment]
As this is a new feature, this certainly needs an entry in the vimperator/NEWS file. Other than that, I think we should change :reader to :set [no]readermode, to be consistent with things like :set [no]fullscreen.

**Comment by seanmorton** [comment]
I'm not sure about making Reader View an option. It only affects the current tab and is not supported on all webpages. To me, options seem to be reserved for things that have a more persistent effect. For example, setting fullscreen in ```.vimperatorrc``` would make sense if the user wanted the browser to always open in fullscreen, but this behaviour wouldn't make sense with reader view. Since reader view is effectively just navigating to the same page with a different layout, I think it makes sense to keep it as a mapping.

**Comment by gkatsev** [comment]
Yeah, I think keeping it as `gr` to mirror `gf` for viewsource is probably the best course of action.

**Pull request closed without merging**
