### PR TITLE
Move from comprehensions to arrays (#398)

### PR DESCRIPTION
**Pull request by gkatsev**

### CODE REVIEW

**Comment by maxauthority** [comment]
Looks good! But does it work? :) Then we probably should push that quite soon, as other such big patches tend to bitrot quite fast.

**Comment by gkatsev** [comment]
Others say it works. I'd want to code review this before merging.

**Comment by reepush** [comment]
@gkatsev I have created branch [comprehensions-review](https://github.com/reepush/vimperator-labs/tree/comprehensions-review) with working mappings and history search, removed comments and proper indentation. Could you change the branch of this pull request to it?

**Comment by reepush** [comment]
Mappings and history search are fixed in _comprehensions_ too. I want to keep comments with assertions, that's why there is a new branch.

**Comment by gkatsev** [comment]
Sure, https://github.com/vimperator/vimperator-labs/pull/486

**Pull request closed without merging**
