### PR TITLE
Remove about:vimperator page.

### PR DESCRIPTION
**Pull request by stepshal**
Same reason as removing of regressions.js

### CODE REVIEW

**Comment by maxauthority** [comment]
As it doesn't really add much to the overall experience (and the design of that page is dated anyway), let's get rid of it. But shouldn't we then also get rid of about_background.png and about.html?

**Comment by stepshal** [comment]
@maxauthority what files should be deleted with then? about.css and icon.png?

**Comment by maxauthority** [comment]
Yes, i think the whole skin/ directory can be deleted. I'll remove them myself just after merging that PR.

**Comment by maxauthority** [comment]
Ah, icon.png is referenced by the install.rdf, so have an icon for the .xpi. But I think about.css is really good to delete.

**Pull request merged**
