### PR TITLE
Comprehensions review

### PR DESCRIPTION
**Pull request by gkatsev**
Thanks @reepush, I ended up making the couple of changes to get this in tonight.

### CODE REVIEW

**Comment by reepush** [comment]
Thanks for the changes. Looking at code I see that branch [comprehensions](https://github.com/vimperator/vimperator-labs/commit/06d695b46f23b1780c5db8259a747d004f966e5e) was merged (with commented asserts) and not a [comprehension-review](https://github.com/reepush/vimperator-labs/commit/e3a3443a39fef1b2849d2a5eedb8c6aa18d92c1b) one (without asserts and with right indentation).

**Comment by reepush** [comment]
I think it will be easier if I make a PR for asserts deletion, so you wouldn't bother reverting and merging again.

**Comment by reepush** [comment]
Remove commented asserts – #493

**Comment by gkatsev** [comment]
Huh, I could've sworn that I used the correct branch...
I'll get a 3.13.1 out tonight, thanks for noticing.

**Pull request merged**
