### PR TITLE
optional xselectpaste to allow X selection paste buffer

### PR DESCRIPTION
**Pull request by pale3**
This commit reverts pasteClipboard function to be optional. By default `xselectpaste` is turned off. To use `<S-Insert>` selection paste, one needs to
specify `set xselectpaste` in his `.vimperatorrc`

### CODE REVIEW

**Comment by SammysHP** [comment]
Probably this should be more platform independent (Windows users don't have an X selection).

**Comment by maxauthority** [comment]
One of the reasons we also removed pasting the X11 selection with S-Insert was, that it broke the command line. So if you have an :open prompt and press shift-insert, doesn't the first "gray" completion suggestion (often something like "amazon" for the search engine) stay in the buffer?

**Comment by pale3** [comment]
@maxauthority 
Hm, this is true, but can be fixed by removing `tempStr3` from value of element. I tested this! If you like I can push fix for this issue.

@SammysHP 
I am not sure what is your recommendations. Do you think that we should inform user if he enable this options and OS is other than Linux, or something else?

**Comment by maxauthority** [comment]
Sorry for the late answer.

Ok, if this is fixed, I guess we might re-add selection pasting support.

However, since most modern Linux (and also Windows IIRC) programs treat s-insert as clipboard paste, I'd propose keeping shift-insert untouched (your patch actually also disables shift-insert for windows/mac users if i read it correctly). But we could add a Shift-Ctrl-Insert to specifically paste the X11 selection (on Linux). This could also easily be mapped to S-Insert, and wouldn't require another option.

Optionally we could go the Gnome-Terminal way and use Shift-Insert for the selection and C-S-Insert for the clipboard, but that patch would need to be written in a way that only Linux gets that mappings, and Shift-Insert on windows/mac keeps their original meaning (=no mapping added, instead of returning or emulating "cmd_paste").

Or any more opinions on this issue by others?

BTW: I just tried <S-Insert> in (Linux) Gvim, and it does not do anything ;)

**Comment by pale3** [comment]
> Sorry for the late answer.

> Ok, if this is fixed, I guess we might re-add selection pasting support.

I will fix this extra "gray" string passed when `<s-insert>` is pressed
on cmdline.

>However, since most modern Linux (and also Windows IIRC) programs treat s-insert as clipboard paste, I'd propose keeping shift-insert untouched (your patch actually also disables shift-insert for windows/mac users if i read it correctly). But we could add a Shift-Ctrl-Insert to specifically paste the X11 selection (on Linux). This could also easily be mapped to S-Insert, and wouldn't require another option.

No it doesn't disable `<s-insert>` when OS is windows. It will use cmd_paste in this situation.
Even when `xselectionpaste=false`, windows will still  paste on `<s-insert>` if there is something in clipboard.

>Optionally we could go the Gnome-Terminal way and use Shift-Insert for the selection and C-S-Insert for the clipboard, but that patch would need to be written in a way that only Linux gets that mappings, and Shift-Insert on windows/mac keeps their original meaning (=no mapping added, instead of returning or emulating "cmd_paste").

I dont see the reason of using pasting from clipboard on `<c-s-insert>`, while every system out there share same clipboard speicifcation of using `<c-v>`.

>BTW: I just tried in (Linux) Gvim, and it does not do anything ;)

hehe, thats how it is!! ;)

**Comment by maxauthority** [comment]
Thanks for the update, however, I still really don't like having another option for this thing. :)
(And actually that option code would have broken S-Insert for Linux users, which certainly would have expected to paste the clipboard with s-insert (the default behavior also on most browsers on Linux) ;)).

Since the "gray" thing seems to have been fixed (I haven't tested it yet), I propose the following:

Make S-Insert the default on Linux for selection paste, but add some help to the help text of `<S-Insert>`, similar to that text:


```
<S-Insert> pastes the clipboard on Windows and MacOS. In Unix, the default behavior is adding the X11 primary selection. If you don't want that behavior, you can map it to paste the clipboard as well:

:inoremap <S-Insert> <C-v>
:cnoremap <S-Insert> <C-v>

```

Additionally also the NEWS file needs to be updated for the new behavior which a quick reference how the user can map to the old behavior.

One last nitpick:
Instead of `if (liberator.has("Windows") || liberator.has("MacUnix"))`
you should probably just write `if (!liberator.has("Unix") ...` as that should only be Linux/FreeBSD, but would not break if we ever add some other weird OS ;)

**Comment by pale3** [comment]
@maxauthority 
I was bussy lately! Source is modified based on your advice! Please take a look and if fine merge it.

**Comment by maxauthority** [comment]
Thanks, looks good to me now. I commited it. If somebody notices something
weird, please report.

**Pull request merged**
