### PR TITLE
WIP: Various changes to fix latest aurora/nightly

### LINKED ISSUE #231: Vimperator broken in latest Nightly 41.0a1 (2015-05-22)
It does not respond to any key shortcuts, and the theme, key bindings, and other customizations are not loaded, either. It is likely this is just an issue with today's build of Nightly, but in case the issue remains from this point forward, an issue should be documented.

### PR DESCRIPTION
**Pull request by gkatsev**
This is still a WIP.

Fixes #231

### CODE REVIEW

**Comment by Mine02C4** [comment]
In my environment(Firefox Nightly), when trying to enter command mode(push ESC) an error message was shown. When "push down"
```
TypeError: util is undefined liberator.js:252:17
```
in Browser Console and command bar, when "push up"
```
TypeError: this._user[mode] is undefined
```
in command bar.

**Comment by gkatsev** [comment]
@Mine02C4 yep, thanks. This is still far from done :)
Hopefully, by next week I'll have it all fixed up.

**Comment by Mine02C4** [comment]
OK. Sorry for my unnecessary comments in progress.

**Comment by gkatsev** [comment]
No worries. It's good to verify the progress I have made, though, there wasn't much of it.

**Comment by t0b1nux** [comment]
Could someone merge this with master or some new branches such as 'aurora' ?

**Comment by gkatsev** [comment]
It should be fixed on. Can people please test it and report back?
It won't necessarily get rid of all errors or warnings that firefox will print out for vimperator (for example if you tell it to print to terminal and then open up firefox in the terminal) but it should work for the most part.

**Comment by gkatsev** [comment]
Also, the help files seem to be loading in better.

**Comment by alts** [comment]
Running 41.0a2 and it works for me. Thanks! I'm not seeing any errors in the console (just deprecation warnings), but perhaps I'm not looking in the right place.

**Comment by Mine02C4** [comment]
On Nightly(42.0a1), it seems working.

But in Browser Console, 
```
TypeError: tab is undefined utils.js:203:1
```
showed.

P.S.
My build for fd6c8017de76583f5039ecb8f2950b1e2bc99b9d is distributed in
http://vimperator.mine02c4.nagoya/downloads/vimperator-3.10-fixup.xpi

**Comment by Segaja** [comment]
When I start vimp with these changes I get a red command line with this error:

```
Invalid argument: nomenu,noaddons
```

Further more the console sais:

```
JavaScript warning: chrome://liberator/content/base.js, line 316: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create
JavaScript warning: resource://firebug/locale.js, line 68: flags argument of String.prototype.{search,match,replace} is deprecated
vimperator: Load abbreviations dependency: config
vimperator: Load modes dependency: util
vimperator: Load abbreviations dependency: modes
vimperator: Load: abbreviations
vimperator: Load: autocommands
vimperator: Load: buffer
vimperator: Load liberator dependency: services
vimperator: Load commandline dependency: liberator
vimperator: Load commandline dependency: storage
vimperator: Load commandline dependency: template
vimperator: Load: commandline
vimperator: Load: commands
vimperator: Load: completion
vimperator: Load: editor
vimperator: Load: events
vimperator: Load: finder
vimperator: Load: hints
vimperator: Load: io
vimperator: Load: javascript
vimperator: Load: mappings
vimperator: Load: marks
vimperator: Load highlight dependency: styles
vimperator: Load options dependency: highlight
JavaScript warning: chrome://liberator/content/style.js, line 263: flags argument of String.prototype.{search,match,replace} is deprecated
vimperator: Load: options
JavaScript warning: chrome://liberator/content/options.js, line 44: Error: __noSuchMethod__ is deprecated
```

but the most part seems to work.

**Comment by Segaja** [comment]
and help is still not working for me.

**Comment by NgrNxk** [comment]
Thank you!
The newest fixup-nightly works fine here:

Vimperator:	3.10pre (created: 2015/07/16 13:02:02)
Firefox:		Mozilla/5.0 (Windows NT 6.3; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0

**Comment by gkatsev** [comment]
Ah, possibly extra stuff changed in nightly. I'm running aurora, currently. I'll have to grab nightly and see what else breaks.

**Comment by t0b1nux** [comment]
Of course there is still a lot of work to be done before working properly but some basic features of vimperator start begin again usable. A great thanks for that work !

**Comment by Segaja** [comment]
Some more error lines I found in the console output:

```
JavaScript error: chrome://liberator/content/editor.js, line 481: NS_NOINTERFACE: Component returned failure code: 0x80004002 (NS_NOINTERFACE) [nsIInterfaceRequestor.getInterface]
JavaScript error: chrome://liberator/content/editor.js, line 481: NS_NOINTERFACE: Component returned failure code: 0x80004002 (NS_NOINTERFACE) [nsIInterfaceRequestor.getInterface]
```

**Comment by t0b1nux** [comment]
Using firefox 42.0a1 (compiled on 2015-07-16), vimperator bar is red and show following text: "TypeError: 'stopPropagation'' called on a object that does not implement interface Event." followed by a link to a comment of this thread. I also activated IGNORE ALL KEYS by pressing <INSERT> and couldn't deactivate it.

**Comment by t0b1nux** [comment]
I Installed vimperator as compiled with the repo and after restarting, firefox give me this error:
```
1437121024672	addons.xpi-utils	WARN	Error: XPI database modified after shutdown began (resource://gre/modules/addons/XPIProvider.jsm -> resource://gre/modules/addons/XPIProviderUtils.js:428:17) JS Stack trace: this.XPIDatabase.saveChanges@XPIProviderUtils.js:428:17 < XPIDB_updateActiveAddons@XPIProviderUtils.js:1374:9 < XPI_shutdown@XPIProvider.jsm:2454:7 < _startProvider/AMProviderShutdown/<@AddonManager.jsm:718:21 < Promise@Promise-backend.js:381:5 < _startProvider/AMProviderShutdown@AddonManager.jsm:716:16 < Barrier/this.client.addBlocker/promise</trigger@AsyncShutdown.jsm:686:23 < Barrier.prototype<._wait@AsyncShutdown.jsm:830:7 < Barrier.prototype<.wait@AsyncShutdown.jsm:814:28 < AddonManagerInternal.shutdownManager<@AddonManager.jsm:1105:15
```
Is it related to vimperator or is it a bug of Firefox internals ?

**Comment by Segaja** [comment]
I solved my problem with the Invalid argument from above: FF doesn't has an addonbar anymore and doesn't show the menu bar in default. so I just removed the specific line from my .vimperatorrc

**Comment by diefans** [comment]
```set gui=tabs,nonavigation``` == ```Invalid Argument```
I was able to disable the locationbar...

**Comment by Segaja** [comment]
When will this PR be merged? It does fix the worst errors on nightly and is definitely an improvement.

**Comment by t0b1nux** [comment]
I totally agree with you but there is still a lot of things to be done before vimperator starts being usable again. So rather than merging, I think it would be more interesting to correct the remaining problems. Furthermore, this changes might be breaking vimperator on stable firefox, no ?

**Comment by gkatsev** [comment]
It does fix most of the bad stuff, so, I might merge it soon. Also, while it shouldn't break stable firefox, it could possibly break on older firefox that vimperator currently claims to support. So, I guess I should verify that before merging.

**Comment by maxauthority** [comment]
We could also just push the minVersion quite high if that makes merging
easier, since for the others there is still vimperator 3.8.3.

**Comment by gkatsev** [comment]
That makes sense, though, I'd like to see how far back the support is before bumping the low end. I'll *definitely* get to it this week since I had a lot more going on this weekend than I thought.

**Comment by gkatsev** [comment]
So, I tested the current ESR release (38) of firefox and it works. I'll bump the minimum version to that and then merge.

**Comment by gkatsev** [comment]
I believe this mostly fixes everything. I'll merge now and release later tonight.

**Pull request merged**
